<?php

namespace JC\BlogBundle\Repository;

use JC\BlogBundle\Entity\Connectes;
use Symfony\Component\DependencyInjection\Dump\Container;
use Symfony\Component\BrowserKit\Request;
use Symfony\Component\Validator\Constraints\DateTime;
use Doctrine\ORM\EntityManager;

/**
 * ConnectesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConnectesRepository extends \Doctrine\ORM\EntityRepository
{


    public function visitorNumber(){
        $qb = $this->createQueryBuilder('u')
            ->select('u')
            ->from('JCBlogBundle:Connectes', 'u')
           ;

        return $qb  ->getQuery()
                    ->getMaxResults();
    }


}